[project]
name = "simple-wasapi-player"
version = "1.0.0"
description = "Simple wav file player using WASAPI"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "comtypes>=1.4.11",
    "pycaw>=20240210",
]
